/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PriorityTargetsRouteImport } from './routes/priority-targets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PriorityTargetsRoute = PriorityTargetsRouteImport.update({
  id: '/priority-targets',
  path: '/priority-targets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pipeline': typeof PipelineRoute
  '/priority-targets': typeof PriorityTargetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pipeline': typeof PipelineRoute
  '/priority-targets': typeof PriorityTargetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pipeline': typeof PipelineRoute
  '/priority-targets': typeof PriorityTargetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pipeline' | '/priority-targets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pipeline' | '/priority-targets'
  id: '__root__' | '/' | '/pipeline' | '/priority-targets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PipelineRoute: typeof PipelineRoute
  PriorityTargetsRoute: typeof PriorityTargetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priority-targets': {
      id: '/priority-targets'
      path: '/priority-targets'
      fullPath: '/priority-targets'
      preLoaderRoute: typeof PriorityTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PipelineRoute: PipelineRoute,
  PriorityTargetsRoute: PriorityTargetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
